practice_attributes = [
    {"name": "Play Soccer", "attribute_category": "sport"},
    {"name": "Play Basketball", "attribute_category": "sport"},
    {"name": "Play Volleyball", "attribute_category": "sport"},
    {"name": "Play Pickleball", "attribute_category": "sport"},
    {"name": "Play Tennis", "attribute_category": "sport"},
    {"name": "Play Frisbee", "attribute_category": "sport"},
    {"name": "Play Baseball", "attribute_category": "sport"},
    {"name": "Play Softball", "attribute_category": "sport"},
    {"name": "Laps at a Track", "attribute_category": "sport"},
    {"name": "Go Cycling", "attribute_category": "movement"},
    {"name": "Go Hiking", "attribute_category": "movement"},
    {"name": "Go Swimming", "attribute_category": "movement"},
    {"name": "Go Climbing", "attribute_category": "movement"},
    {"name": "Do Yoga", "attribute_category": "movement"},
    {"name": "Do Stretching", "attribute_category": "movement"},
    {"name": "Do Calisthenics", "attribute_category": "movement"},
    {"name": "Practice Martial Arts", "attribute_category": "movement"},
    {"name": "Practice Tai Chi", "attribute_category": "movement"},
    {"name": "Practice Nei Gong", "attribute_category": "movement"},
    {"name": "Do Pilates", "attribute_category": "movement"},
    {"name": "Lift Weights", "attribute_category": "movement"},
    {"name": "Go for a Run", "attribute_category": "movement"},
    {"name": "Take a Walk", "attribute_category": "movement"},

    {"name": "Draw or Sketch", "attribute_category": "craft"},
    {"name": "Paint", "attribute_category": "craft"},
    {"name": "Create Digital Art", "attribute_category": "craft"},
    {"name": "Make Pottery", "attribute_category": "craft"},
    {"name": "Sculpt with Clay", "attribute_category": "craft"},
    {"name": "Make Origami", "attribute_category": "craft"},
    {"name": "Knit", "attribute_category": "craft"},
    {"name": "Crochet", "attribute_category": "craft"},
    {"name": "Do Woodburning", "attribute_category": "craft"},
    {"name": "Make Resin Art", "attribute_category": "craft"},
    {"name": "Create Beadwork", "attribute_category": "craft"},
    {"name": "Sew", "attribute_category": "craft"},
    {"name": "Do Embroidery", "attribute_category": "craft"},
    {"name": "Make a Collage", "attribute_category": "craft"},
    {"name": "Scrapbook", "attribute_category": "craft"},
    {"name": "Make a Zine", "attribute_category": "craft"},
    {"name": "Do Macramé", "attribute_category": "craft"},
    {"name": "Make Prints", "attribute_category": "craft"},
    {"name": "Practice Calligraphy", "attribute_category": "craft"},

    {"name": "Play Guitar", "attribute_category": "instrument"},
    {"name": "Play Piano", "attribute_category": "instrument"},
    {"name": "Play Drums", "attribute_category": "instrument"},
    {"name": "Play Bass", "attribute_category": "instrument"},
    {"name": "Play Violin", "attribute_category": "instrument"},
    {"name": "Sing or Practice Voice", "attribute_category": "instrument"},
    {"name": "Play Flute", "attribute_category": "instrument"},
    {"name": "Play Synthesizer", "attribute_category": "instrument"},
    {"name": "Play Ukulele", "attribute_category": "instrument"},
    {"name": "Play Didgeridoo", "attribute_category": "instrument"},
    {"name": "Use a Sound Bowl", "attribute_category": "instrument"},
    {"name": "Use a Tuning Fork", "attribute_category": "instrument"},
    {"name": "Play a Gong", "attribute_category": "instrument"},
    {"name": "Use a Shruti Box", "attribute_category": "instrument"},
    {"name": "Chant a Mantra", "attribute_category": "sound_practice"},
    {"name": "Chant or Sing", "attribute_category": "sound_practice"},

    {"name": "Practice Vipassana Meditation", "attribute_category": "meditation_type"},
    {"name": "Practice Zazen", "attribute_category": "meditation_type"},
    {"name": "Practice Samatha", "attribute_category": "meditation_type"},
    {"name": "Practice Metta Bhavana", "attribute_category": "meditation_type"},
    {"name": "Do a Body Scan Meditation", "attribute_category": "meditation_type"},
    {"name": "Do Mantra Meditation", "attribute_category": "meditation_type"},
    {"name": "Do Breath Awareness Meditation", "attribute_category": "meditation_type"},
    {"name": "Do Visualization Meditation", "attribute_category": "meditation_type"},
    {"name": "Use the RAIN Method", "attribute_category": "meditation_type"},
    {"name": "Practice Choiceless Awareness", "attribute_category": "meditation_type"},
    {"name": "Do Mindful Walking", "attribute_category": "meditation_type"},
    {"name": "Consult the I Ching", "attribute_category": "spiritual_tool"},
    {"name": "Do Chakra Focus", "attribute_category": "spiritual_tool"},

    {"name": "Keep a Journal", "attribute_category": "writing"},
    {"name": "Write Poetry", "attribute_category": "writing"},
    {"name": "Freewrite", "attribute_category": "writing"},
    {"name": "Write a Gratitude List", "attribute_category": "writing"},
    {"name": "CBT Thought Log", "attribute_category": "writing"},
    {"name": "Value Check-In", "attribute_category": "writing"},
    {"name": "Review Your Goals", "attribute_category": "writing"},
    {"name": "Write a Vision Statement", "attribute_category": "writing"},
    {"name": "Track Your Mood", "attribute_category": "writing"},
    {"name": "Dream Journal Entry", "attribute_category": "writing"},
    {"name": "Prompt/Response Journaling", "attribute_category": "writing"},
    {"name": "Write a Story", "attribute_category": "writing"},
    {"name": "Write a Letter", "attribute_category": "writing"},

    {"name": "Read a Book", "attribute_category": "learning"},
    {"name": "Take Notes", "attribute_category": "learning"},
    {"name": "Create a Mind Map", "attribute_category": "learning"},
    {"name": "Practice a Language", "attribute_category": "learning"},
    {"name": "Do a Memory Exercise", "attribute_category": "learning"},
    {"name": "Do a Focus Drill", "attribute_category": "learning"},
    {"name": "Study a Course", "attribute_category": "learning"},
    {"name": "Listen to an Audiobook", "attribute_category": "learning"},
    {"name": "Watch a Documentary", "attribute_category": "learning"},
    {"name": "Use Flashcards", "attribute_category": "learning"},
    {"name": "Play a Logic Game", "attribute_category": "learning"},
    {"name": "Reflect on a Podcast", "attribute_category": "learning"},

    {"name": "Set a Phone Limit", "attribute_category": "digital_habit"},
    {"name": "Take a Social Media Break", "attribute_category": "digital_habit"},
    {"name": "Skip Morning Screen Time", "attribute_category": "digital_habit"},
    {"name": "Use a Focus Timer", "attribute_category": "digital_habit"},
    {"name": "Clean Out Your Apps", "attribute_category": "digital_habit"},
    {"name": "Turn Off Notifications", "attribute_category": "digital_habit"},
    {"name": "Block Deep Work Time", "attribute_category": "digital_habit"},
    {"name": "Do a Digital Fast", "attribute_category": "digital_habit"},
    {"name": "Clean Up Your Email", "attribute_category": "digital_habit"},
    {"name": "Unfollow and Declutter Feeds", "attribute_category": "digital_habit"},

    {"name": "Get Sunlight Exposure", "attribute_category": "nature"},
    {"name": "Do Barefoot Grounding", "attribute_category": "nature"},
    {"name": "Take a Cold Shower or Dip", "attribute_category": "nature"},
    {"name": "Go Forest Bathing", "attribute_category": "nature"},
    {"name": "Watch the Moon", "attribute_category": "nature"},
    {"name": "Tend Your Garden", "attribute_category": "nature"},
    {"name": "Watch the Clouds", "attribute_category": "nature"},
    {"name": "Journal Outdoors", "attribute_category": "nature"},
    {"name": "Listen to Natural Sounds", "attribute_category": "nature"},

    {"name": "Do It Solo", "attribute_category": "trait"},
    {"name": "Do It Socially", "attribute_category": "trait"},
    {"name": "Take It Outdoors", "attribute_category": "trait"},
    {"name": "Keep It Indoors", "attribute_category": "trait"},
    {"name": "Choose Something Low Barrier", "attribute_category": "trait"},
    {"name": "Pick a High-Focus Activity", "attribute_category": "trait"},
    {"name": "Pick Something Restorative", "attribute_category": "trait"},
    {"name": "Pick Something Energizing", "attribute_category": "trait"},
    {"name": "Choose Something Playful", "attribute_category": "trait"},
    {"name": "Choose Something Creative", "attribute_category": "trait"},
    {"name": "Choose Something Reflective", "attribute_category": "trait"},
    {"name": "Choose Something Expressive", "attribute_category": "trait"},
    {"name": "Choose a Tactile Activity", "attribute_category": "trait"},
    {"name": "Choose a Technical Practice", "attribute_category": "trait"},
    {"name": "Practice in Silence", "attribute_category": "trait"},
    {"name": "Use a Guided Practice", "attribute_category": "trait"},
    {"name": "Follow a Ritual", "attribute_category": "trait"},
    {"name": "Do Something Goal-Oriented", "attribute_category": "trait"}
]
